### ISSUE TITLE
KenLM checkpoint

### ISSUE THREAD

**Issue by TuanBC** [SUNGBEOMCHOI/Korean-Streaming-ASR#2]
Hello, thanks for the nice implementation and pretrained model of Korean ASR.

I am testing with the code, but I couldn't find the pretrained checkpoint for this kenlm model. Could you provide the checkpoint of that model for testing too?

**Comment by SUNGBEOMCHOI** [comment]
Regarding the pretrained checkpoint for the KenLM model, unfortunately, we have removed the checkpoint and it is no longer available. During our evaluations, we found that the KenLM model primarily provides performance improvements in very specialized domains. Based on this, we generally recommend not using language models like KenLM, especially if your application has a broad scope or does not fit into those niche areas.
