### ISSUE TITLE
pretrained 불러오는 방법

### ISSUE THREAD

**Issue by DavidSunHo** [SUNGBEOMCHOI/Korean-Streaming-ASR#3]
안녕하세요. 구글 드라이브에서 제공하고 있는 .th 파일을 불러오는 방법이 hub에서 모델을 불러와서 load하는 걸까요? Demucs 클래스를 선언하고 불러오는 걸까요?

**Comment by SUNGBEOMCHOI** [comment]
src/utils/transcriber.py의 33번째 줄에 load_denoiser_model 함수가 선언되어있습니다. 이 함수를 통해 denoiser 모델을 load하게 됩니다.
